const fs = require('fs');
const path = require('path');

// SEO-optimized descriptions for every tool
const descriptions = {
    'add-page-number-to-pdf.php': 'Add page numbers to PDF online for free. Customize position, font, size, and style. No sign-up needed — fast, secure, and works in your browser.',
    'add-watermark-to-pdf.php': 'Add text or image watermarks to PDF files online for free. Customize opacity, position, and font. Secure, instant, no software required.',
    'age-calculator.php': 'Free age calculator online. Calculate your exact age in years, months, days, hours, and minutes from your date of birth. Instant results, no sign-up required.',
    'apy-calculator.php': 'Free APY calculator online. Calculate Annual Percentage Yield on savings accounts, CDs, and investments. Compare APY vs APR and maximize your returns.',
    'bmi-calculator.php': 'Free BMI calculator online. Calculate your Body Mass Index instantly — enter your height and weight to find out if you are underweight, healthy, or overweight.',
    'brokerage-calculator.php': 'Free brokerage calculator online. Calculate stock trading brokerage fees, taxes, and net profit/loss for NSE, BSE, MCX trades. Compare brokers instantly.',
    'cagr-calculator.php': 'Free CAGR calculator online. Calculate Compound Annual Growth Rate for investments, revenue, and portfolios. Understand your true investment growth rate.',
    'calendar-generator.php': 'Free online calendar generator. Create and download printable monthly or yearly calendars in PDF format. Customize with events and holidays instantly.',
    'car-loan-emi-calculator.php': 'Free car loan EMI calculator. Calculate your monthly car loan installments, total interest payable, and amortization schedule. Plan your auto financing smartly.',
    'case-converter.php': 'Free case converter online. Convert text to UPPERCASE, lowercase, Title Case, camelCase, snake_case, and more instantly. Perfect for developers and writers.',
    'color-picker.php': 'Free online color picker tool. Pick, convert, and generate colors in HEX, RGB, HSL, and CMYK formats. Create color palettes for your web and design projects.',
    'compound-interest-calculator.php': 'Free compound interest calculator online. Calculate compound interest earned on savings and investments. Compare monthly, quarterly, and yearly compounding effects.',
    'compress-pdf.php': 'Compress PDF files online for free. Reduce PDF file size without quality loss. Fast, secure compression — no software needed, works in your browser.',
    'csv-to-pdf.php': 'Convert CSV to PDF online for free. Turn spreadsheet data and CSV files into professional PDF documents instantly. No software downloads required.',
    'delete-pdf-pages.php': 'Delete pages from PDF online for free. Remove single or multiple pages from any PDF quickly and securely. No sign-up required — instant results.',
    'discount-calculator.php': 'Free discount calculator online. Calculate sale price, discount amount, and savings percentage instantly. Perfect for shopping, retail pricing, and deals.',
    'dwg-to-pdf.php': 'Convert DWG to PDF online for free. Transform AutoCAD DWG and DXF files into PDF documents. Fast, secure conversion with high-quality output.',
    'emi-calculator.php': 'Free EMI calculator online. Calculate monthly loan EMI for home, car, or personal loans. Get full amortization schedule and total interest payable instantly.',
    'epf-calculator.php': 'Free EPF calculator online. Calculate Employee Provident Fund maturity amount, monthly contributions, and interest. Plan your retirement savings effectively.',
    'epub-to-pdf.php': 'Convert EPUB to PDF online for free. Transform e-book EPUB files into PDF documents instantly. Preserve formatting, fonts, and images. No software needed.',
    'excel-to-pdf.php': 'Convert Excel to PDF online for free. Transform XLS and XLSX spreadsheets into PDF documents. Preserve formatting, charts, and formulas. Fast and secure.',
    'fd-calculator.php': 'Free FD calculator online. Calculate Fixed Deposit maturity amount, interest earned, and returns for any bank. Compare FD rates and plan your savings.',
    'find-replace-text.php': 'Free Find and Replace text tool online. Search and replace words, phrases, or characters in bulk. Supports case-sensitive, regex, and whole-word replacements.',
    'flat-vs-reducing-rate-calculator.php': 'Free flat vs reducing rate calculator. Compare flat interest rates and reducing balance rates on loans. Find the true cost of your loan and make smarter decisions.',
    'flatten-pdf.php': 'Flatten PDF online for free. Convert interactive PDF forms and annotations into non-editable flat PDFs. Fast, secure, and free — no software required.',
    'gratuity-calculator.php': 'Free gratuity calculator online. Calculate your gratuity amount based on years of service and last drawn salary. Know your end-of-service benefits instantly.',
    'gst-calculator.php': 'Free GST calculator online. Calculate GST amount, inclusive/exclusive GST prices for 5%, 12%, 18%, and 28% tax slabs. Instant results for India GST.',
    'home-equity-loan-calculator.php': 'Free home equity loan calculator. Calculate HELOC monthly payments, interest costs, and loan eligibility based on your home value and existing mortgage.',
    'home-loan-emi-calculator.php': 'Free home loan EMI calculator. Calculate housing loan monthly installments, total interest, and complete amortization schedule. Plan your dream home financing.',
    'hra-calculator.php': 'Free HRA calculator online. Calculate your House Rent Allowance tax exemption as per Income Tax rules. Know the exact HRA deduction you are eligible for.',
    'html-to-pdf.php': 'Convert HTML to PDF online for free. Transform web pages and HTML files into PDF documents. Preserve styling, images, and layout. Instant conversion.',
    'income-tax-calculator.php': 'Free income tax calculator for India. Calculate your income tax liability under old and new tax regime for FY 2024-25. Plan deductions and save more tax.',
    'inflation-calculator.php': 'Free inflation calculator online. Calculate the real value of money over time, purchasing power loss, and future price using historical inflation rates.',
    'investment-returns-calculator.php': 'Free investment returns calculator. Calculate total returns, CAGR, and profit/loss on your investments with detailed year-by-year growth breakdown.',
    'ipynb-to-pdf.php': 'Convert IPYNB to PDF online for free. Transform Jupyter Notebook files into PDF documents. Preserve code cells, outputs, and markdown. Fast and secure.',
    'jfif-to-pdf.php': 'Convert JFIF to PDF online for free. Transform JFIF image files into PDF documents instantly. Combine multiple images into one PDF. No software needed.',
    'jpg-to-pdf.php': 'Convert JPG to PDF online for free. Transform JPEG images into PDF documents instantly. Merge multiple JPG files into one PDF. Secure and fast.',
    'json-formatter.php': 'Free JSON formatter and validator online. Format, beautify, minify, and validate JSON data. Syntax highlighting and error detection for developers.',
    'json-to-pdf.php': 'Convert JSON to PDF online for free. Transform JSON data files into formatted PDF documents instantly. Easy conversion with clean output. No sign-up needed.',
    'loan-eligibility-calculator.php': 'Free loan eligibility calculator. Check how much home, car, or personal loan you can get based on your income, expenses, and credit profile. Instant results.',
    'lock-pdf.php': 'Lock and password-protect PDF online for free. Add 256-bit AES encryption to your PDF files instantly. Secure confidential documents with strong passwords.',
    'lumpsum-calculator.php': 'Free lumpsum calculator online. Calculate returns on one-time investment in mutual funds or stocks. See wealth growth with compound interest over any period.',
    'margin-calculator.php': 'Free margin calculator online. Calculate profit margin, markup percentage, and gross margin for products and services. Essential for pricing and business planning.',
    'markdown-to-pdf.php': 'Convert Markdown to PDF online for free. Transform MD files and Markdown text into PDF documents. Preserve headings, lists, code blocks, and formatting.',
    'merge-pdf.php': 'Merge PDF files online for free. Combine multiple PDF documents into one file instantly. Reorder pages, merge unlimited files — fast, secure, no sign-up.',
    'mobi-to-pdf.php': 'Convert MOBI to PDF online for free. Transform Kindle MOBI e-book files into PDF documents. Preserve formatting and content. Instant, free conversion.',
    'mutual-fund-returns-calculator.php': 'Free mutual fund returns calculator. Calculate absolute returns, CAGR, and wealth gained on your mutual fund investments. Analyze SIP and lump sum performance.',
    'nps-calculator.php': 'Free NPS calculator online. Calculate National Pension System maturity corpus, monthly pension, and returns. Plan your retirement with India NPS scheme.',
    'nsc-calculator.php': 'Free NSC calculator online. Calculate National Savings Certificate maturity amount, interest earned at 5-year tenure. Secure government-backed investment planning.',
    'offer-letter-generator.php': 'Free online offer letter generator. Create professional job offer letters quickly. Customize salary, designation, joining date, and company details. Download as PDF.',
    'password-generator.php': 'Free password generator online. Create strong, secure, random passwords with custom length and character sets. Generate 100% secure passwords instantly.',
    'payroll-sheet-generator.php': 'Free payroll sheet generator online. Create monthly employee payroll reports with salary breakdown, deductions, and net pay. Download as Excel or PDF.',
    'pdf-editor.php': 'Free PDF editor online. Edit PDF text, images, and pages directly in your browser. Add annotations, fill forms, and modify PDF files without software.',
    'pdf-metadata-editor.php': 'Free PDF metadata editor online. View and edit PDF title, author, subject, keywords, and creation date. Update document properties without Adobe Acrobat.',
    'pdf-to-audio.php': 'Convert PDF to audio online for free. Listen to any PDF document using text-to-speech conversion. Supports multiple voices and playback speeds. No sign-up needed.',
    'pdf-to-csv.php': 'Convert PDF to CSV online for free. Extract tables and data from PDF files into CSV spreadsheet format. Accurate data extraction for analysis. Fast and secure.',
    'pdf-to-epub.php': 'Convert PDF to EPUB online for free. Transform PDF documents into e-book EPUB format for Kindle, Kobo, and e-readers. Preserve text and formatting.',
    'pdf-to-excel.php': 'Convert PDF to Excel online for free. Extract tables from PDF into editable XLS/XLSX spreadsheets. Accurate data extraction with formatting preserved.',
    'pdf-to-html.php': 'Convert PDF to HTML online for free. Transform PDF documents into web-ready HTML pages. Preserve layout, text, and images. Instant, browser-based conversion.',
    'pdf-to-ipynb.php': 'Convert PDF to Jupyter Notebook (IPYNB) online for free. Extract text and code from PDF into IPYNB format for data science work. Fast and secure.',
    'pdf-to-jfif.php': 'Convert PDF to JFIF online for free. Transform PDF pages into JFIF image files instantly. High-quality output, adjustable resolution. No software needed.',
    'pdf-to-jpg.php': 'Convert PDF to JPG online for free. Extract PDF pages as high-quality JPEG images. Download individually or as a ZIP. Fast, secure, no sign-up required.',
    'pdf-to-json.php': 'Convert PDF to JSON online for free. Extract structured text and data from PDF files into JSON format. Ideal for developers and data processing pipelines.',
    'pdf-to-markdown.php': 'Convert PDF to Markdown online for free. Transform PDF documents into clean Markdown text. Preserve headings, lists, and structure. Perfect for developers.',
    'pdf-to-mobi.php': 'Convert PDF to MOBI online for free. Transform PDF documents into Kindle-compatible MOBI e-book format. Read PDFs on any Kindle device or app.',
    'pdf-to-ocr.php': 'PDF OCR converter online for free. Extract and recognize text from scanned PDFs using Optical Character Recognition. Convert image PDFs to searchable text.',
    'pdf-to-png.php': 'Convert PDF to PNG online for free. Transform PDF pages into high-quality PNG images. Transparent background support. Fast, secure, no software required.',
    'pdf-to-ppt.php': 'Convert PDF to PowerPoint (PPT/PPTX) online for free. Transform PDF slides into editable presentations. Preserve layout and images. Fast and accurate.',
    'pdf-to-psd.php': 'Convert PDF to PSD online for free. Transform PDF files into editable Photoshop PSD format. Preserve layers and design elements. Instant, free conversion.',
    'pdf-to-svg.php': 'Convert PDF to SVG online for free. Transform PDF files into scalable vector graphics. Perfect for web use, printing, and design workflows. No sign-up needed.',
    'pdf-to-text.php': 'Convert PDF to text online for free. Extract all text content from PDF files instantly. Supports scanned PDFs with OCR. Fast, secure, browser-based conversion.',
    'pdf-to-tiff.php': 'Convert PDF to TIFF online for free. Transform PDF pages into high-resolution TIFF image files. Ideal for archiving and printing. Fast and secure.',
    'pdf-to-webp.php': 'Convert PDF to WebP online for free. Transform PDF pages into modern WebP image format for fast web loading. High quality with smaller file sizes.',
    'pdf-to-word.php': 'Convert PDF to Word (DOCX) online for free. Transform PDF documents into editable Microsoft Word files. Preserve text, tables, and formatting accurately.',
    'pdf-to-xml.php': 'Convert PDF to XML online for free. Extract structured content from PDF files into XML format. Ideal for data processing, integration, and automation.',
    'percentage-calculator.php': 'Free percentage calculator online. Calculate percentage of a number, percentage increase/decrease, and find what percent one number is of another. Instant results.',
    'personal-loan-calculator.php': 'Free personal loan EMI calculator. Calculate monthly installments, total interest, and repayment schedule for personal loans. Compare loan offers instantly.',
    'png-to-pdf.php': 'Convert PNG to PDF online for free. Transform PNG images into PDF documents. Combine multiple PNGs into one PDF file. Fast, secure, no software needed.',
    'pnr-to-pdf.php': 'Convert PNR to PDF online for free. Generate PDF travel documents from PNR booking codes. Ideal for ticket printing and travel records. Instant conversion.',
    'ppf-calculator.php': 'Free PPF calculator online. Calculate Public Provident Fund maturity amount, yearly interest, and 15-year returns. Tax-free investment under Section 80C.',
    'ppt-to-pdf.php': 'Convert PowerPoint to PDF online for free. Transform PPT and PPTX presentations into PDF documents. Preserve slides, animations, and formatting. Fast and secure.',
    'pto-calculator.php': 'Free PTO calculator online. Calculate Paid Time Off accrual, balance, and usage for employees. Track vacation days, sick leave, and personal time off.',
    'qr-code-generator.php': 'Free QR code generator online. Create custom QR codes for URLs, text, WiFi, contact info, and more. Download as PNG or SVG. No sign-up required.',
    'rd-calculator.php': 'Free RD calculator online. Calculate Recurring Deposit maturity amount and interest earned with quarterly compounding. Plan your monthly savings goal.',
    'refinance-calculator.php': 'Free mortgage refinance calculator. Calculate monthly savings, break-even point, and total interest saved from refinancing. Make smarter refinancing decisions.',
    'remove-extra-spaces.php': 'Free online tool to remove extra spaces from text. Trim leading, trailing, and multiple spaces between words instantly. Clean and format text effortlessly.',
    'reorder-pdf-pages.php': 'Reorder PDF pages online for free. Drag and drop to rearrange pages in any order. Reorganize your PDF documents quickly — no software or sign-up needed.',
    'repair-pdf.php': 'Repair corrupted PDF files online for free. Fix damaged, unreadable, or broken PDF documents and recover your content. Fast and secure browser-based repair.',
    'retirement-calculator.php': 'Free retirement calculator online. Calculate how much you need to save for a comfortable retirement. Factor in inflation, life expectancy, and investment returns.',
    'reverse-mortgage-calculator.php': 'Free reverse mortgage calculator for seniors 62+. Calculate HECM loan limits, monthly income, and tenure. Plan your retirement income from home equity.',
    'reverse-text.php': 'Free reverse text converter online. Flip text backwards, mirror words, or reverse letters instantly. Fun text effects for creative projects and social media.',
    'rotate-pdf.php': 'Rotate PDF pages online for free. Rotate all or individual pages by 90°, 180°, or 270°. Fix upside-down or sideways PDF pages instantly. No software needed.',
    'rtf-to-pdf.php': 'Convert RTF to PDF online for free. Transform Rich Text Format documents into PDF files. Preserve fonts, formatting, and images. Instant, secure conversion.',
    'salary-calculator.php': 'Free salary calculator online. Calculate take-home pay, gross to net salary, HRA, PF deductions, and in-hand salary with India tax slabs. Accurate and instant.',
    'scientific-calculator.php': 'Free scientific calculator online. Advanced math with trigonometry, logarithms, exponents, factorial, and more. Perfect for students, engineers, and scientists.',
    'shreelipi-to-pdf.php': 'Convert Shreelipi text to PDF online for free. Transform Shreelipi font documents into PDF files instantly. Preserve Gujarati and other Indian language fonts.',
    'simple-calculator.php': 'Free simple calculator online. Perform basic arithmetic — addition, subtraction, multiplication, and division. Easy-to-use calculator for everyday calculations.',
    'simple-interest-calculator.php': 'Free simple interest calculator online. Calculate interest earned on principal, rate, and time. Understand your savings and loan interest with instant results.',
    'sip-calculator.php': 'Free SIP calculator online. Calculate Systematic Investment Plan returns, wealth gained, and maturity amount for mutual fund SIPs. Plan smart monthly investments.',
    'speech-to-pdf.php': 'Convert speech to PDF online for free. Record or transcribe your voice and convert speech to text into a PDF document. Fast, accurate, and easy to use.',
    'split-pdf.php': 'Split PDF online for free. Divide PDF files into multiple documents by page range or export every page as a separate PDF. Fast, secure, no sign-up required.',
    'step-up-sip-calculator.php': 'Free Step-Up SIP calculator. Calculate returns with annually increasing SIP contributions. See how top-up SIP accelerates your wealth creation over time.',
    'sukanya-samriddhi-yojana-calculator.php': 'Free Sukanya Samriddhi Yojana (SSY) calculator. Calculate maturity amount and interest for your daughter\'s SSY account. Government-backed tax-free savings scheme.',
    'svg-to-pdf.php': 'Convert SVG to PDF online for free. Transform scalable vector graphics into PDF documents. Preserve vector quality and design. Instant, secure, free conversion.',
    'swp-calculator.php': 'Free SWP calculator online. Calculate Systematic Withdrawal Plan returns, monthly withdrawals, and remaining corpus from mutual fund investments. Smart retirement planning.',
    'tax-calculator.php': 'Free tax calculator online. Calculate income tax, deductions, and net tax payable under India\'s old and new tax regime for FY 2024-25. Accurate and instant.',
    'tds-calculator.php': 'Free TDS calculator online. Calculate Tax Deducted at Source on salary, rent, interest, and professional fees. Know your TDS liability as per Indian tax rules.',
    'text-comparision.php': 'Free text comparison tool online. Compare two texts side by side and highlight differences, additions, and deletions. Perfect for proofreading and code review.',
    'text-to-pdf.php': 'Convert text to PDF online for free. Transform plain TXT files and text content into PDF documents. Customize fonts and layout. Fast, secure, no software needed.',
    'text-to-slug.php': 'Free text to URL slug converter online. Generate SEO-friendly slugs from any text. Remove special characters, spaces, and format for clean, readable URLs.',
    'tiff-to-pdf.php': 'Convert TIFF to PDF online for free. Transform TIFF image files into PDF documents. Combine multiple TIFF pages into one PDF. Fast, secure, free conversion.',
    'timesheet-calculator.php': 'Free timesheet calculator online. Calculate total work hours, overtime, and payroll for employees. Track daily time entries, breaks, and weekly totals instantly.',
    'unit-converter.php': 'Free unit converter online. Convert length, weight, temperature, volume, area, speed, and more. 50+ unit types with instant metric to imperial conversion.',
    'unlock-pdf.php': 'Unlock PDF online for free. Remove password protection and restrictions from PDF files instantly. Access locked PDFs without software. Fast and secure.',
    'webp-to-pdf.php': 'Convert WebP to PDF online for free. Transform WebP image files into PDF documents. Combine multiple WebP images into one PDF. Fast, secure, no sign-up needed.',
    'word-counter.php': 'Free word counter online. Count words, characters, sentences, and paragraphs in real-time. Calculate reading time and keyword density. Instant, privacy-first tool.',
    'word-to-pdf.php': 'Convert Word to PDF online for free. Transform DOC and DOCX files into PDF documents. Preserve fonts, tables, images, and formatting. Fast and secure.',
    'xml-to-pdf.php': 'Convert XML to PDF online for free. Transform XML data files into formatted PDF documents. Preserve structure and content. Instant, browser-based conversion.',
};

const toolsDir = 'views/tools';
let updatedCount = 0;

for (const [file, desc] of Object.entries(descriptions)) {
    const filePath = path.join(toolsDir, file);
    if (!fs.existsSync(filePath)) continue;

    let code = fs.readFileSync(filePath, 'utf8');

    // Replace $page_description = "anything" with new description
    const newCode = code.replace(/(\$page_description\s*=\s*)(["']).*?\2/is, `$1"${desc}"`);
    
    if (newCode !== code) {
        fs.writeFileSync(filePath, newCode);
        updatedCount++;
    }
}

console.log('Updated ' + updatedCount + ' tool files with SEO-optimized meta descriptions.');
