const fs = require('fs');
const path = require('path');

// SEO-optimized titles for every tool (55-65 chars ideal)
const titles = {
    'add-page-number-to-pdf.php': 'Add Page Numbers to PDF Online Free - WordsCompare',
    'add-watermark-to-pdf.php': 'Add Watermark to PDF Online Free - WordsCompare',
    'age-calculator.php': 'Age Calculator - Calculate Exact Age Online Free',
    'apy-calculator.php': 'APY Calculator - Annual Percentage Yield Calculator Online',
    'bmi-calculator.php': 'BMI Calculator - Body Mass Index Calculator Online Free',
    'brokerage-calculator.php': 'Brokerage Calculator - Calculate Stock Trading Fees Online',
    'cagr-calculator.php': 'CAGR Calculator - Compound Annual Growth Rate Calculator',
    'calendar-generator.php': 'Calendar Generator - Create Printable Calendars Online Free',
    'car-loan-emi-calculator.php': 'Car Loan EMI Calculator - Calculate Auto Loan Installments',
    'case-converter.php': 'Case Converter - Convert Text Case Online Free',
    'color-picker.php': 'Color Picker - Pick & Convert Colors HEX RGB HSL Online',
    'compound-interest-calculator.php': 'Compound Interest Calculator - Calculate Investment Returns',
    'compress-pdf.php': 'Compress PDF Online Free - Reduce PDF File Size',
    'csv-to-pdf.php': 'CSV to PDF Converter - Convert CSV Files to PDF Online Free',
    'delete-pdf-pages.php': 'Delete PDF Pages Online Free - Remove Pages from PDF',
    'discount-calculator.php': 'Discount Calculator - Calculate Sale Price & Savings Online',
    'dwg-to-pdf.php': 'DWG to PDF Converter - Convert AutoCAD Files to PDF Online',
    'emi-calculator.php': 'EMI Calculator - Calculate Loan EMI Online Free',
    'epf-calculator.php': 'EPF Calculator - Employee Provident Fund Calculator Online',
    'epub-to-pdf.php': 'EPUB to PDF Converter - Convert eBook to PDF Online Free',
    'excel-to-pdf.php': 'Excel to PDF Converter - Convert XLS/XLSX to PDF Online Free',
    'fd-calculator.php': 'FD Calculator - Fixed Deposit Maturity Calculator Online',
    'find-replace-text.php': 'Find and Replace Text Online Free - WordsCompare',
    'flat-vs-reducing-rate-calculator.php': 'Flat vs Reducing Rate Calculator - Compare Loan Rates',
    'flatten-pdf.php': 'Flatten PDF Online Free - Convert Interactive PDF to Flat PDF',
    'gratuity-calculator.php': 'Gratuity Calculator - Calculate Gratuity Amount Online Free',
    'gst-calculator.php': 'GST Calculator - Calculate GST Amount Online Free India',
    'home-equity-loan-calculator.php': 'Home Equity Loan Calculator - HELOC Payment Calculator',
    'home-loan-emi-calculator.php': 'Home Loan EMI Calculator - Housing Loan Calculator Online',
    'hra-calculator.php': 'HRA Calculator - House Rent Allowance Exemption Calculator',
    'html-to-pdf.php': 'HTML to PDF Converter - Convert Web Pages to PDF Online Free',
    'income-tax-calculator.php': 'Income Tax Calculator India FY 2024-25 - Free Online Tool',
    'inflation-calculator.php': 'Inflation Calculator - Calculate Purchasing Power Online',
    'investment-returns-calculator.php': 'Investment Returns Calculator - Calculate ROI Online Free',
    'ipynb-to-pdf.php': 'IPYNB to PDF - Convert Jupyter Notebook to PDF Online Free',
    'jfif-to-pdf.php': 'JFIF to PDF Converter - Convert JFIF Images to PDF Online',
    'jpg-to-pdf.php': 'JPG to PDF Converter - Convert JPEG Images to PDF Online Free',
    'json-formatter.php': 'JSON Formatter & Validator - Beautify JSON Online Free',
    'json-to-pdf.php': 'JSON to PDF Converter - Convert JSON Data to PDF Online Free',
    'loan-eligibility-calculator.php': 'Loan Eligibility Calculator - Check Loan Amount Online Free',
    'lock-pdf.php': 'Lock PDF Online Free - Password Protect PDF with Encryption',
    'lumpsum-calculator.php': 'Lumpsum Calculator - Calculate One-Time Investment Returns',
    'margin-calculator.php': 'Margin Calculator - Calculate Profit Margin & Markup Online',
    'markdown-to-pdf.php': 'Markdown to PDF Converter - Convert MD Files to PDF Online',
    'merge-pdf.php': 'Merge PDF Online Free - Combine PDF Files into One',
    'mobi-to-pdf.php': 'MOBI to PDF Converter - Convert Kindle Books to PDF Online',
    'mutual-fund-returns-calculator.php': 'Mutual Fund Returns Calculator - Calculate MF Returns Online',
    'nps-calculator.php': 'NPS Calculator - National Pension System Calculator Online',
    'nsc-calculator.php': 'NSC Calculator - National Savings Certificate Calculator',
    'offer-letter-generator.php': 'Offer Letter Generator - Create Job Offer Letters Online Free',
    'password-generator.php': 'Password Generator - Create Strong Secure Passwords Online',
    'payroll-sheet-generator.php': 'Payroll Sheet Generator - Create Payroll Reports Online Free',
    'pdf-editor.php': 'PDF Editor Online Free - Edit PDF Files in Your Browser',
    'pdf-metadata-editor.php': 'PDF Metadata Editor - Edit PDF Properties Online Free',
    'pdf-to-audio.php': 'PDF to Audio Converter - Convert PDF to Speech Online Free',
    'pdf-to-csv.php': 'PDF to CSV Converter - Extract PDF Data to CSV Online Free',
    'pdf-to-epub.php': 'PDF to EPUB Converter - Convert PDF to eBook Online Free',
    'pdf-to-excel.php': 'PDF to Excel Converter - Extract PDF Tables to XLS Online',
    'pdf-to-html.php': 'PDF to HTML Converter - Convert PDF to Web Page Online Free',
    'pdf-to-ipynb.php': 'PDF to Jupyter Notebook - Convert PDF to IPYNB Online Free',
    'pdf-to-jfif.php': 'PDF to JFIF Converter - Convert PDF Pages to JFIF Online Free',
    'pdf-to-jpg.php': 'PDF to JPG Converter - Convert PDF Pages to JPEG Online Free',
    'pdf-to-json.php': 'PDF to JSON Converter - Extract PDF Data to JSON Online Free',
    'pdf-to-markdown.php': 'PDF to Markdown Converter - Convert PDF to MD Online Free',
    'pdf-to-mobi.php': 'PDF to MOBI Converter - Convert PDF to Kindle Format Online',
    'pdf-to-ocr.php': 'PDF OCR - Extract Text from Scanned PDF Online Free',
    'pdf-to-png.php': 'PDF to PNG Converter - Convert PDF Pages to PNG Online Free',
    'pdf-to-ppt.php': 'PDF to PowerPoint Converter - Convert PDF to PPTX Online Free',
    'pdf-to-psd.php': 'PDF to PSD Converter - Convert PDF to Photoshop Online Free',
    'pdf-to-svg.php': 'PDF to SVG Converter - Convert PDF to Vector Graphics Online',
    'pdf-to-text.php': 'PDF to Text Converter - Extract Text from PDF Online Free',
    'pdf-to-tiff.php': 'PDF to TIFF Converter - Convert PDF to TIFF Images Online Free',
    'pdf-to-webp.php': 'PDF to WebP Converter - Convert PDF to WebP Images Online',
    'pdf-to-word.php': 'PDF to Word Converter - Convert PDF to DOCX Online Free',
    'pdf-to-xml.php': 'PDF to XML Converter - Convert PDF Data to XML Online Free',
    'percentage-calculator.php': 'Percentage Calculator - Calculate Percentages Online Free',
    'personal-loan-calculator.php': 'Personal Loan Calculator - Calculate EMI & Interest Online',
    'png-to-pdf.php': 'PNG to PDF Converter - Convert PNG Images to PDF Online Free',
    'pnr-to-pdf.php': 'PNR to PDF Converter - Generate PDF from PNR Online Free',
    'ppf-calculator.php': 'PPF Calculator - Public Provident Fund Calculator Online',
    'ppt-to-pdf.php': 'PowerPoint to PDF Converter - Convert PPT/PPTX to PDF Online',
    'pto-calculator.php': 'PTO Calculator - Calculate Paid Time Off Balance Online Free',
    'qr-code-generator.php': 'QR Code Generator - Create Custom QR Codes Online Free',
    'rd-calculator.php': 'RD Calculator - Recurring Deposit Maturity Calculator Online',
    'refinance-calculator.php': 'Refinance Calculator - Calculate Mortgage Savings Online Free',
    'remove-extra-spaces.php': 'Remove Extra Spaces from Text Online Free - WordsCompare',
    'reorder-pdf-pages.php': 'Reorder PDF Pages Online Free - Rearrange PDF Pages',
    'repair-pdf.php': 'Repair PDF Online Free - Fix Corrupted PDF Files Instantly',
    'retirement-calculator.php': 'Retirement Calculator - Plan Your Retirement Savings Online',
    'reverse-mortgage-calculator.php': 'Reverse Mortgage Calculator - HECM Loan Calculator Online',
    'reverse-text.php': 'Reverse Text Converter - Flip Text Backwards Online Free',
    'rotate-pdf.php': 'Rotate PDF Pages Online Free - Fix PDF Page Orientation',
    'rtf-to-pdf.php': 'RTF to PDF Converter - Convert Rich Text Format to PDF Online',
    'salary-calculator.php': 'Salary Calculator - Calculate Take-Home Pay & CTC Online',
    'scientific-calculator.php': 'Scientific Calculator Online Free - Advanced Math Calculator',
    'shreelipi-to-pdf.php': 'Shreelipi to PDF Converter - Convert Shreelipi Fonts to PDF',
    'simple-calculator.php': 'Simple Calculator Online Free - Basic Arithmetic Calculator',
    'simple-interest-calculator.php': 'Simple Interest Calculator - Calculate SI Online Free',
    'sip-calculator.php': 'SIP Calculator - Systematic Investment Plan Returns Calculator',
    'speech-to-pdf.php': 'Speech to PDF Converter - Convert Voice to PDF Online Free',
    'split-pdf.php': 'Split PDF Online Free - Divide PDF into Multiple Files',
    'step-up-sip-calculator.php': 'Step-Up SIP Calculator - Calculate Increasing SIP Returns',
    'sukanya-samriddhi-yojana-calculator.php': 'Sukanya Samriddhi Yojana Calculator - SSY Returns Online',
    'svg-to-pdf.php': 'SVG to PDF Converter - Convert Vector Graphics to PDF Online',
    'swp-calculator.php': 'SWP Calculator - Systematic Withdrawal Plan Calculator Online',
    'tax-calculator.php': 'Tax Calculator India FY 2024-25 - Income Tax Calculator Online',
    'tds-calculator.php': 'TDS Calculator - Calculate Tax Deducted at Source Online Free',
    'text-comparision.php': 'Text Comparison Tool - Compare Two Texts Online Free',
    'text-to-pdf.php': 'Text to PDF Converter - Convert TXT Files to PDF Online Free',
    'text-to-slug.php': 'Text to Slug Converter - Generate URL Slugs Online Free',
    'tiff-to-pdf.php': 'TIFF to PDF Converter - Convert TIFF Images to PDF Online Free',
    'timesheet-calculator.php': 'Timesheet Calculator - Calculate Work Hours & Pay Online',
    'unit-converter.php': 'Unit Converter Online Free - Convert Length Weight Temperature',
    'unlock-pdf.php': 'Unlock PDF Online Free - Remove PDF Password & Restrictions',
    'webp-to-pdf.php': 'WebP to PDF Converter - Convert WebP Images to PDF Online Free',
    'word-counter.php': 'Word Counter Online Free - Count Words Characters Sentences',
    'word-to-pdf.php': 'Word to PDF Converter - Convert DOC/DOCX to PDF Online Free',
    'xml-to-pdf.php': 'XML to PDF Converter - Convert XML Data to PDF Online Free',
};

const toolsDir = 'views/tools';
let updatedCount = 0;

for (const [file, title] of Object.entries(titles)) {
    const filePath = path.join(toolsDir, file);
    if (!fs.existsSync(filePath)) continue;

    let code = fs.readFileSync(filePath, 'utf8');

    // Replace $page_title = "anything" with new title
    const newCode = code.replace(/(\$page_title\s*=\s*)(["']).*?\2/is, `$1"${title}"`);

    if (newCode !== code) {
        fs.writeFileSync(filePath, newCode);
        updatedCount++;
    }
}

console.log('Updated ' + updatedCount + ' tool files with SEO-optimized page titles.');
