<?php 
$page_title = "Privacy Policy";
$page_description = "Learn how Snapy Tools protects your privacy and handles your data";
$page_keywords = "privacy policy, data protection, webtools privacy";
include '../includes/header.php'; 
?>

<!-- Page Content -->
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-8 border shadow-sm p-4">
            <article>
                <header class="mb-5 text-center">
                    <h1 class="display-5 fw-bold">Privacy Policy</h1>
                    <p class="lead">Your privacy is important to us</p>
                </header>

                <section class="mb-5">
                    <h2 class="h4 mb-3">Data Collection</h2>
                    <p><?php echo $site_name; ?> is designed with privacy in mind. Most of our tools process your data locally in your browser and do not send it to our servers. We do not collect or store:</p>
                    <ul>
                        <li>Personal information you input into our tools</li>
                        <li>Results generated by our tools</li>
                        <li>Your browsing history or usage patterns</li>
                    </ul>
                    <p>For certain tools that require server processing, we may temporarily process your data but do not store it permanently.</p>
                </section>

                <section class="mb-5">
                    <h2 class="h4 mb-3">Information We Do Collect</h2>
                    <p>We collect minimal information to operate and improve our service:</p>
                    <ul>
                        <li>Basic usage statistics (tool popularity, not individual usage)</li>
                        <li>Anonymous analytics to improve user experience</li>
                        <li>Error reports to help fix bugs</li>
                    </ul>
                    <p>This information is aggregated and cannot be used to identify individual users.</p>
                </section>

                <section class="mb-5">
                    <h2 class="h4 mb-3">Cookies and Tracking</h2>
                    <p><?php echo $site_name; ?> uses minimal cookies:</p>
                    <ul>
                        <li>Session cookies for basic functionality</li>
                        <li>Preference cookies for user settings</li>
                    </ul>
                    <p>We do not use third-party tracking cookies or advertising trackers. Our analytics are privacy-focused and do not identify individual users.</p>
                </section>

                <section class="mb-5">
                    <h2 class="h4 mb-3">Third-Party Services</h2>
                    <p>We may use limited third-party services for:</p>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h3 class="h5 card-title">Hosting</h3>
                                    <p class="card-text">Our servers are hosted with reputable providers with strong privacy policies.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h3 class="h5 card-title">Analytics</h3>
                                    <p class="card-text">We use privacy-focused analytics to understand tool usage without tracking individuals.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p>We carefully select service providers who respect user privacy.</p>
                </section>

                <section class="mb-5">
                    <h2 class="h4 mb-3">Data Security</h2>
                    <p>We implement appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include:</p>
                    <ul>
                        <li>Secure HTTPS connections for all communications</li>
                        <li>Regular security reviews of our code and infrastructure</li>
                        <li>Minimal data retention policies</li>
                    </ul>
                </section>

                <section class="mb-4">
                    <h2 class="h4 mb-3">Changes to This Policy</h2>
                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.</p>
                    <p>You are advised to review this Privacy Policy periodically for any changes.</p>
                </section>

                <section class="mb-4">
                    <h2 class="h4 mb-3">Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, please <a href="<?php echo $base_url; ?>contact">contact us</a>.</p>
                    <p class="text-muted small">Last Updated: <?php echo date('F j, Y'); ?></p>
                </section>
            </article>
        </div>
    </div>
</div>

<?php include '../includes/footer.php'; ?>